export const action_definitions = {
  FETCH_METADATA: "FETCH_METADATA",
  FETCH_METADATA_SUCCEEDED: "FETCH_METADATA_SUCCEEDED",
  FETCH_METADATA_FAILED: "FETCH_METADATA_FAILED",
  FETCH_METADATA_ABORTED: "FETCH_METADATA_ABORTED",
  INITIALIZE_SIGNATURE_SEARCH: "INITIALIZE_SIGNATURE_SEARCH",
  MATCH_ENTITY: "MATCH_ENTITY",
  MATCH_FAILED: "MATCH_FAILED",
  UPDATE_RESOLVED_ENTITIES: "UPDATE_RESOLVED_ENTITIES",
  FIND_SIGNATURES: "FIND_SIGNATURES",
  FIND_SIGNATURES_SUCCEEDED: "FIND_SIGNATURES_SUCCEEDED",
  FIND_SIGNATURES_FAILED: "FIND_SIGNATURES_FAILED",
  INITIALIZE_SIGCOM: "INITIALIZE_SIGCOM"
}
